"""empty message

Revision ID: 9d3536dc6370
Revises: 49020ea24619
Create Date: 2022-05-01 14:46:59.111541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3536dc6370'
down_revision = '49020ea24619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'userId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'taskId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'pictures',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'pictures',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reviews', 'taskId',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'userId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
