"""empty message

Revision ID: 2055c1e9d35a
Revises: ffdc0a98111c
Create Date: 2022-01-20 15:02:50.676748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2055c1e9d35a'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('price', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('pictures', sa.String(length=280), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
